webdata:
  # Mapping host volume for development:
  image: tianon/true
  volumes:
    - "../web:/srv/www/dev.test"
mongodb:
  image: blueimp/mongodb:3.2
  # Debug access:
  ports:
    - "27017:27017"
redis:
  image: blueimp/redis:3.0
  # Debug access:
  ports:
    - "6379:6379"
elasticsearch:
  image: blueimp/elasticsearch:2.1
  # Debug access:
  ports:
    - "9200:9200"
php:
  image: dev/php
  links:
    - mongodb
    - redis
    - elasticsearch
  volumes_from:
    - webdata
  environment:
    - SSMTP_AUTH_USER
    - SSMTP_AUTH_PASS
    - SSH_PRIVATE_KEY
    - SSH_KNOWN_HOSTS
nginx:
  image: dev/nginx
  links:
    - php
  volumes_from:
    - webdata
  environment:
    - DH_PARAM
    - SSL_CRT
    - SSL_KEY
  ports:
    - "80:80"
    - "443:443"
