webdata:
  # Mapping host volume for development:
  image: busybox
  volumes:
  - "../web:/srv/www/dev.test"
secretconfig:
  image: develop/secretconfig
  environment:
  - SSMTP_AUTH_USER
  - SSMTP_AUTH_PASS
  - SSL_CRT
  - SSL_KEY
  - SSH_PRIVATE_KEY
  - SSH_PUBLIC_KEY
  - SSH_KNOWN_HOSTS
mongodbdata:
  image: develop/mongodbdata
mongodb:
  image: develop/mongodb
  volumes_from:
  - mongodbdata
  # Debug access:
  ports:
  - "27017:27017"
redisdata:
  image: develop/redisdata
redis:
  image: develop/redis
  volumes_from:
  - redisdata
  # Debug access:
  ports:
  - "6379:6379"
elasticsearchdata:
  image: develop/elasticsearchdata
elasticsearch:
  image: develop/elasticsearch
  volumes_from:
  - elasticsearchdata
  # Debug access:
  ports:
  - "9200:9200"
php:
  image: develop/php
  links:
  - mongodb
  - redis
  - elasticsearch
  volumes_from:
  - secretconfig
  - webdata
cron:
  image: develop/php
  links:
  - mongodb
  - redis
  - elasticsearch
  volumes_from:
  - secretconfig
  - webdata
  entrypoint: "cronservice"
nginx:
  image: develop/nginx
  links:
  - php
  volumes_from:
  - secretconfig
  - webdata
  ports:
  - "80:80"
  - "443:443"
