webdata:
  # Mapping host volume for development:
  image: tianon/true
  volumes:
    - "../web:/srv/www/dev.test"
mongodbdata:
  image: tianon/true
  volumes:
    - /data/db
mongodb:
  image: blueimp/mongodb:3.0
  volumes_from:
    - mongodbdata
  # Debug access:
  ports:
    - "27017:27017"
redisdata:
  image: tianon/true
  volumes:
    - /data/redis
redis:
  image: blueimp/redis:3.0
  volumes_from:
    - redisdata
  # Debug access:
  ports:
    - "6379:6379"
elasticsearchdata:
  image: tianon/true
  volumes:
    - /usr/share/elasticsearch/data
elasticsearch:
  image: blueimp/elasticsearch:1.6
  volumes_from:
    - elasticsearchdata
  # Debug access:
  ports:
    - "9200:9200"
php:
  image: dev/php
  links:
    - mongodb
    - redis
    - elasticsearch
  volumes_from:
    - webdata
  environment:
    - SSMTP_AUTH_USER
    - SSMTP_AUTH_PASS
    - SSH_PRIVATE_KEY
    - SSH_KNOWN_HOSTS
cron:
  image: dev/php
  links:
    - mongodb
    - redis
    - elasticsearch
  volumes_from:
    - webdata
  environment:
    - SSMTP_AUTH_USER
    - SSMTP_AUTH_PASS
    - SSH_PRIVATE_KEY
    - SSH_KNOWN_HOSTS
  command: "superd"
nginx:
  image: dev/nginx
  links:
    - php
  volumes_from:
    - webdata
  environment:
    - DH_PARAM
    - SSL_CRT
    - SSL_KEY
  ports:
    - "80:80"
    - "443:443"
